name: dotnet-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
  # Permite que você execute este fluxo de trabalho manualmente na guia Ações
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest 
        
    steps:
    - name: Checando do GitHub Action
      uses: actions/checkout@v3
    
    - name: Configurando o .NETCore
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x   
  
    - name: Restaurando dependências
      run: dotnet restore
      working-directory: ./source/TRILHAR.Services.Api
      
    - name: Contruíndo em Release com dotnet build --no-restore --configuration Release
      run: dotnet build --no-restore --configuration Release
      working-directory: ./source/TRILHAR.Services.Api

    - name: Publicando com dotnet publish --no-build --configuration Release --output ./publish
      run: dotnet publish --no-build --configuration Release --output ./publish
      working-directory: ./source/TRILHAR.Services.Api
      
    # - name: Check publish directory
    #   run: ls -l ./source/TRILHAR.Services.Api/publish
      
    - name: Subindo artefatos para serem usados no próximo fluxo
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./source/TRILHAR.Services.Api/publish

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Baixando artefatos criados no fluxo anterior
      if: success()
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: ./artifact

    - name: Implantando no servidor FTP
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./artifact/
        server-dir: httpdocs/webapp/
        protocol: ftps
        dangerous-clean-slate: true
        retries: 2   # Tentativas adicionais
        retry-delay: 30  # Atraso entre tentativas em segundos
