name: dotnet-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest 
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x   
  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./source/TRILHAR.Services.Api
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./source/TRILHAR.Services.Api

    - name: Publish
      run: dotnet publish --no-build --configuration Release --output ./publish
      working-directory: ./source/TRILHAR.Services.Api
      
    - name: Check publish directory
      run: ls -l ./source/TRILHAR.Services.Api/publish
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: ./source/TRILHAR.Services.Api/publish

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts created at previous job
      uses: actions/download-artifact@v3
      with:
        name: publish
        path: ./artifact

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./artifact
        server-dir: /httpdocs/webapp
        protocol: ftps
        dangerous-clean-slate: true
