name: dotnet-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest 
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: List files
      run: ls -R
  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: TRILHAR.Services.Api # Atualize com base no resultado do `ls`
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: TRILHAR.Services.Api # Atualize com base no resultado do `ls`
      
    - name: Publish artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: TRILHAR.Services.Api/bin/Release/net6.0/publish/
