name: dotnet-workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checando do GitHub Action
        uses: actions/checkout@v4

      - name: Configurando o .NETCore
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restaurando dependências
        run: dotnet restore --locked-mode
        working-directory: ./source/TRILHAR.Services.Api

      - name: Construindo em Release
        run: dotnet build --no-restore --configuration Release
        working-directory: ./source/TRILHAR.Services.Api

      - name: Publicando o projeto
        run: dotnet publish --no-build --configuration Release --output ./publish
        working-directory: ./source/TRILHAR.Services.Api

      - name: Criar app_offline.htm temporariamente
        run: echo "<h1>Aplicação temporariamente indisponível para manutenção.</h1>" > ./source/TRILHAR.Services.Api/publish/app_offline.htm

      - name: Subindo artefatos
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./source/TRILHAR.Services.Api/publish

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixando artefatos
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: ./artifact

      - name: Deploy com aplicação offline
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./artifact/
          server-dir: httpdocs/webapp/
          exclude: |
            **/*.log
          retries: 2
          retry-delay: 30

      - name: Remover app_offline.htm (reativar site)
        run: rm ./artifact/app_offline.htm

      - name: Reenviar para remover o app_offline.htm do servidor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./artifact/
          server-dir: httpdocs/webapp/
          exclude: |
            **/*.log
          retries: 2
          retry-delay: 30
